/* 开口说 · 内容源
 * 唯一内容源：所有场景与句子都在这里，index.html / app.js 不写死任何句子。
 * 结构：GROUPS 分组 → SCENES 场景 → lines[3] 三句，按使用频率从高到低排列。
 *   freq 3=★★★ 几乎每次都用 | 2=★★ 常用 | 1=★ 备用/进阶
 *   tip  什么时候用、说的时候注意什么
 *   reply 对方大概率怎么回你（听懂对方的回答，比会说更重要）
 *   alt  换个说法（同义替换，随口能换）
 */
const GROUPS = [
  { id: "travel", name: "出行", icon: "✈️", desc: "从值机到问路，落地就能用" },
  { id: "hotel",  name: "住宿", icon: "🏨", desc: "入住、要东西、退房" },
  { id: "food",   name: "吃饭", icon: "🍽️", desc: "点单、加料、买单" },
  { id: "shop",   name: "购物", icon: "🛍️", desc: "挑、试、结账、退换" },
  { id: "life",   name: "生活", icon: "🏥", desc: "看病、银行、理发、手机卡" },
  { id: "social", name: "社交", icon: "💬", desc: "见面、闲聊、道谢、告别" },
  { id: "work",   name: "工作", icon: "🧑‍💼", desc: "介绍、开会、电话、请求" },
  { id: "sos",    name: "应急", icon: "🆘", desc: "没听懂、求助、丢东西" },
  { id: "sea",    name: "东南亚", icon: "🛺", desc: "砍价、嘟嘟车、寺庙、按摩、拒绝拉客" },
  { id: "yijing", name: "易经专业", icon: "☯️", desc: "用英语介绍你的行业、解释易经八字风水" }
];

const SCENES = [
/* ============ 出行 ============ */
{ id:"checkin", group:"travel", name:"机场值机", en:"Check-in", icon:"🛄", lines:[
  { en:"I'd like to check in for my flight to London.", zh:"我想办去伦敦这班的值机。", freq:3,
    tip:"走到柜台第一句，把目的地说出来最省事。递上护照就行。",
    reply:"Passport, please. / How many bags are you checking?",
    alt:"Checking in for London, please." },
  { en:"Just one bag to check, and this is my carry-on.", zh:"托运一件，这个随身带。", freq:2,
    tip:"主动说清楚，能省掉一轮问答。carry-on = 随身行李。",
    reply:"Please put it on the scale.",
    alt:"One checked bag, one carry-on." },
  { en:"Could I get an aisle seat, please?", zh:"能给我一个靠走道的座位吗？", freq:1,
    tip:"aisle 读 /aɪl/，s 不发音。靠窗是 window seat。",
    reply:"Sure, 24C. / I'm afraid we only have middle seats left.",
    alt:"Any chance of a window seat?" }
]},
{ id:"security", group:"travel", name:"安检登机", en:"Security & Boarding", icon:"🛂", lines:[
  { en:"Do I need to take out my laptop?", zh:"电脑需要拿出来吗？", freq:3,
    tip:"各国规矩不一样，问一句比被叫回去重过一遍强。",
    reply:"Yes, in a separate tray. / No, you can leave it in.",
    alt:"Does the laptop stay in the bag?" },
  { en:"Which gate is the flight to Paris boarding at?", zh:"去巴黎那班在哪个登机口？", freq:2,
    tip:"gate 临时改是常事，登机前再确认一次。",
    reply:"Gate B12, it's down that way.",
    alt:"Where's gate B12?" },
  { en:"Sorry, is this the line for boarding?", zh:"请问这是登机排的队吗？", freq:1,
    tip:"美式 line，英式 queue。排错队很常见，问一句不丢人。",
    reply:"Yes, but they're boarding group 2 right now.",
    alt:"Is this the queue for group 3?" }
]},
{ id:"onboard", group:"travel", name:"飞机上", en:"On the Plane", icon:"💺", lines:[
  { en:"Excuse me, I think that's my seat.", zh:"不好意思，那好像是我的座位。", freq:3,
    tip:"I think 是缓冲，比直接说 that's my seat 客气很多。",
    reply:"Oh sorry! Let me move.",
    alt:"Sorry, I'm in 24C — is that this one?" },
  { en:"Could I have some water, please?", zh:"能给我一杯水吗？", freq:2,
    tip:"要什么都套 Could I have ... please，最万能的一句。",
    reply:"Still or sparkling?",
    alt:"Water, please. / A coffee, please." },
  { en:"Would you mind if I put my seat back?", zh:"我把座椅放下来可以吗？", freq:1,
    tip:"注意 Would you mind 的回答是反的：No 才是可以。",
    reply:"No, go ahead.",
    alt:"Is it okay if I recline?" }
]},
{ id:"customs", group:"travel", name:"入境海关", en:"Immigration", icon:"🛃", lines:[
  { en:"I'm here on vacation, for about ten days.", zh:"我来旅游，大概待十天。", freq:3,
    tip:"目的+时长一次说完，是海关最想听的答案。出差说 on business。",
    reply:"Where are you staying?",
    alt:"Just traveling. / I'm here for business." },
  { en:"I'm staying at the Hilton downtown.", zh:"我住在市区的希尔顿。", freq:2,
    tip:"住址必问，建议提前把酒店名和街道存手机里。",
    reply:"Do you have the address?",
    alt:"With a friend, in Brooklyn." },
  { en:"No, I have nothing to declare.", zh:"没有，我没有需要申报的东西。", freq:1,
    tip:"declare 是申报。带了大量现金或食品才需要说 yes。",
    reply:"Okay, enjoy your stay.",
    alt:"Nothing to declare." }
]},
{ id:"taxi", group:"travel", name:"打车", en:"Taxi & Rideshare", icon:"🚕", lines:[
  { en:"Could you take me to this address, please?", zh:"麻烦送我到这个地址。", freq:3,
    tip:"上车第一句。地名念不准就直接把手机屏幕给司机看，配这句最稳。",
    reply:"Sure, hop in.",
    alt:"To the airport, please." },
  { en:"How long does it usually take?", zh:"一般要开多久？", freq:2,
    tip:"赶飞机赶会必问。usually 让对方给平均值而不是拍脑袋。",
    reply:"About twenty minutes, if traffic's okay.",
    alt:"Are we going to hit traffic?" },
  { en:"You can just drop me off here, thanks.", zh:"在这儿放我下来就行，谢谢。", freq:1,
    tip:"drop off = 放下人。堵车时提前下车非常好用。",
    reply:"Right here? Okay.",
    alt:"Anywhere along here is fine." }
]},
{ id:"transit", group:"travel", name:"地铁公交", en:"Public Transit", icon:"🚇", lines:[
  { en:"Does this train go to Central Station?", zh:"这班车到中央车站吗？", freq:3,
    tip:"上车前问站台上的人，一句话避免坐反方向。",
    reply:"Yeah, four stops. / No, you want the other platform.",
    alt:"Is this the right platform for downtown?" },
  { en:"Which stop should I get off at?", zh:"我该在哪站下车？", freq:2,
    tip:"get off 下车（公交地铁火车），出租车/小车是 get out。",
    reply:"Two more stops — I'll tell you.",
    alt:"How many stops is it?" },
  { en:"Where can I buy a ticket?", zh:"在哪儿买票？", freq:1,
    tip:"很多城市买通票更划算，可以接一句 Is there a day pass?",
    reply:"At the machine over there.",
    alt:"Can I pay with my card on board?" }
]},
{ id:"directions", group:"travel", name:"问路", en:"Asking Directions", icon:"🗺️", lines:[
  { en:"Excuse me, how do I get to the museum?", zh:"打扰一下，博物馆怎么走？", freq:3,
    tip:"Excuse me 起手，再问路。别用 Hey。",
    reply:"Go straight and turn left at the lights.",
    alt:"Excuse me, where's the nearest subway?" },
  { en:"Is it walkable from here?", zh:"从这儿走过去远吗？", freq:2,
    tip:"一句话问清该走还是该打车，比问几公里更实用。",
    reply:"It's about ten minutes on foot.",
    alt:"How far is it?" },
  { en:"Sorry, could you show me on the map?", zh:"不好意思，能在地图上指给我看吗？", freq:1,
    tip:"听不懂方向词时的救命句，把手机递过去。",
    reply:"Sure — we're here, and it's right there.",
    alt:"Could you point me in the right direction?" }
]},
{ id:"car", group:"travel", name:"租车加油", en:"Car Rental & Gas", icon:"🚗", lines:[
  { en:"I have a reservation under the name Chen.", zh:"我有预订，姓陈。", freq:3,
    tip:"under the name ... 是所有预订的通用句式，酒店餐厅都能用。",
    reply:"Can I see your license and passport?",
    alt:"I booked online — here's the confirmation." },
  { en:"Is insurance included?", zh:"保险包含在内吗？", freq:2,
    tip:"租车最容易被加价的地方，一定问清楚。",
    reply:"Basic coverage is included, full is extra.",
    alt:"What's not covered?" },
  { en:"Do I need to return it with a full tank?", zh:"还车时需要加满油吗？", freq:1,
    tip:"full tank = 满油。不问清楚可能被收高价油费。",
    reply:"Yes, or we charge you for the fuel.",
    alt:"Where's the nearest gas station?" }
]},

/* ============ 住宿 ============ */
{ id:"hcheckin", group:"hotel", name:"酒店入住", en:"Hotel Check-in", icon:"🔑", lines:[
  { en:"Hi, I have a reservation for two nights.", zh:"你好，我订了两晚。", freq:3,
    tip:"走到前台就说这句，然后递护照，流程自动往下走。",
    reply:"Your name, please? / Passport, please.",
    alt:"Checking in — the name is Chen." },
  { en:"What time is breakfast, and where is it?", zh:"早餐几点、在哪里？", freq:2,
    tip:"两个信息一句问完。接着可问 Is it included?（含早吗）",
    reply:"Seven to ten, on the second floor.",
    alt:"Is breakfast included?" },
  { en:"Could I have a late check-out?", zh:"能晚点退房吗？", freq:1,
    tip:"入住时先问一嘴，常能免费延到下午一两点。",
    reply:"We can do 1 p.m., no charge.",
    alt:"What time is check-out?" }
]},
{ id:"room", group:"hotel", name:"客房问题", en:"Room Requests", icon:"🛎️", lines:[
  { en:"Could you send up some towels, please?", zh:"能送几条毛巾上来吗？", freq:3,
    tip:"send up = 送到房间。换成 water / an extra pillow / a toothbrush 都行。",
    reply:"Of course, room number?",
    alt:"Could I get an extra blanket?" },
  { en:"The air conditioning isn't working.", zh:"空调坏了。", freq:2,
    tip:"报修万能句型：The ... isn't working. 换成 shower / TV / Wi-Fi 即可。",
    reply:"Sorry about that, I'll send someone up.",
    alt:"There's no hot water in my room." },
  { en:"What's the Wi-Fi password?", zh:"Wi-Fi 密码是多少？", freq:1,
    tip:"通常印在房卡套上，找不到就问，几乎每天用。",
    reply:"It's on the back of your key card.",
    alt:"Is the Wi-Fi free?" }
]},
{ id:"hcheckout", group:"hotel", name:"退房", en:"Check-out", icon:"🧾", lines:[
  { en:"I'd like to check out, please.", zh:"我要退房。", freq:3,
    tip:"最标准的退房开场，说完把房卡放柜台上。",
    reply:"Room number? How was your stay?",
    alt:"Checking out — room 512." },
  { en:"Could I leave my luggage here until the afternoon?", zh:"行李能寄存到下午吗？", freq:2,
    tip:"几乎所有酒店都免费寄存，退房后继续玩必备。",
    reply:"Sure, here's your tag.",
    alt:"Do you have luggage storage?" },
  { en:"Could you call me a taxi?", zh:"能帮我叫辆车吗？", freq:1,
    tip:"call sb a taxi = 帮某人叫车。可加 for 8 o'clock 预约时间。",
    reply:"It'll be here in five minutes.",
    alt:"Is there a shuttle to the airport?" }
]}
,
/* ============ 吃饭 ============ */
{ id:"order", group:"food", name:"餐厅点餐", en:"Ordering", icon:"🍝", lines:[
  { en:"I'll have the steak, please.", zh:"我要牛排，谢谢。", freq:3,
    tip:"点餐最地道的说法是 I'll have ...，比 I want 礼貌得多。指着菜单说 I'll have this one 也行。",
    reply:"How would you like it cooked?",
    alt:"Could I get the pasta?" },
  { en:"What do you recommend?", zh:"你推荐什么？", freq:2,
    tip:"看不懂菜单时的万能句，还能顺带练听力。",
    reply:"The salmon is really good today.",
    alt:"What's your most popular dish?" },
  { en:"No onions, please — I'm allergic.", zh:"不要洋葱，我过敏。", freq:1,
    tip:"忌口句型：No ..., please。过敏一定要说 allergic，对方会认真对待。",
    reply:"I'll let the kitchen know.",
    alt:"Could I have it without cheese?" }
]},
{ id:"coffee", group:"food", name:"咖啡店", en:"Coffee Shop", icon:"☕", lines:[
  { en:"A large latte, please.", zh:"一杯大杯拿铁。", freq:3,
    tip:"星巴克的 tall/grande/venti 只在星巴克用，别的店说 small/medium/large。",
    reply:"For here or to go?",
    alt:"Can I get an iced americano?" },
  { en:"To go, please.", zh:"带走，谢谢。", freq:2,
    tip:"美式 to go，英式 takeaway。堂食是 for here / eat in。",
    reply:"That'll be four fifty.",
    alt:"For here, thanks." },
  { en:"Could I get oat milk instead?", zh:"能换成燕麦奶吗？", freq:1,
    tip:"instead 结尾表示替换，改任何东西都能用。",
    reply:"Sure, that's fifty cents extra.",
    alt:"Less ice, please." }
]},
{ id:"fastfood", group:"food", name:"快餐外带", en:"Fast Food", icon:"🍔", lines:[
  { en:"Can I get a number three, please?", zh:"我要三号套餐。", freq:3,
    tip:"快餐店直接报套餐号最快，number three = 三号餐。",
    reply:"What drink would you like with that?",
    alt:"A cheeseburger and fries, please." },
  { en:"That's everything, thanks.", zh:"就这些了，谢谢。", freq:2,
    tip:"对方问 Anything else? 时的收尾句，说完就该付钱了。",
    reply:"Okay, that's nine ninety.",
    alt:"That's it, thanks." },
  { en:"Could I have some ketchup?", zh:"能给点番茄酱吗？", freq:1,
    tip:"要小东西一律 Could I have some ...：napkins 纸巾 / a straw 吸管。",
    reply:"They're right over there.",
    alt:"Could I get a few napkins?" }
]},
{ id:"bill", group:"food", name:"买单", en:"Paying the Bill", icon:"💳", lines:[
  { en:"Could we get the check, please?", zh:"麻烦买单。", freq:3,
    tip:"美式 check，英式 bill。也可以远远地对服务员做个写字手势。",
    reply:"Sure, I'll be right back.",
    alt:"Could we have the bill, when you get a chance?" },
  { en:"Can we pay separately?", zh:"能分开付吗？", freq:2,
    tip:"AA 制不说 AA。分开付 pay separately，平摊说 split it.",
    reply:"Of course — card or cash?",
    alt:"Let's split it." },
  { en:"Is service included?", zh:"服务费包含了吗？", freq:1,
    tip:"决定要不要另给小费的关键一问，欧洲常已含。",
    reply:"Yes, it's on the bill.",
    alt:"Keep the change." }
]},

/* ============ 购物 ============ */
{ id:"browse", group:"shop", name:"逛店选货", en:"Browsing", icon:"👀", lines:[
  { en:"I'm just looking, thanks.", zh:"我先随便看看，谢谢。", freq:3,
    tip:"店员一上来问 Can I help you? 就用这句，礼貌打发，全世界通用。",
    reply:"No problem, let me know if you need anything.",
    alt:"Just browsing, thank you." },
  { en:"Do you have this in a different color?", zh:"这个有别的颜色吗？", freq:2,
    tip:"把 color 换成 size / style 就是另一句。",
    reply:"Let me check in the back.",
    alt:"Do you have this in stock?" },
  { en:"How much is this?", zh:"这个多少钱？", freq:1,
    tip:"没标价才用。听不清价格就问 Sorry, how much was that?",
    reply:"It's twenty-nine ninety-nine.",
    alt:"Is this on sale?" }
]},
{ id:"fitting", group:"shop", name:"试穿尺码", en:"Trying On", icon:"👕", lines:[
  { en:"Can I try this on?", zh:"我能试一下吗？", freq:3,
    tip:"try on 专指试穿。试鞋也是这句。",
    reply:"Sure, the fitting room is over there.",
    alt:"Where's the fitting room?" },
  { en:"Do you have this in a medium?", zh:"这个有 M 码吗？", freq:2,
    tip:"尺码：small / medium / large，或直接说 a size 38。",
    reply:"That's the last one, sorry.",
    alt:"Do you have a bigger size?" },
  { en:"It's a bit too tight. Could I size up?", zh:"有点紧，能换大一号吗？", freq:1,
    tip:"size up 大一号 / size down 小一号，店员一听就懂。",
    reply:"I'll grab you a large.",
    alt:"It doesn't quite fit." }
]},
{ id:"pay", group:"shop", name:"结账", en:"Checking Out", icon:"🧮", lines:[
  { en:"I'll take this one.", zh:"我就要这个。", freq:3,
    tip:"决定买了就说这句，然后走向收银台。",
    reply:"Great, I'll ring you up.",
    alt:"I'll take these, thanks." },
  { en:"Card, please.", zh:"刷卡。", freq:2,
    tip:"对方问 Cash or card? 时两个字搞定。手机支付说 I'll tap.",
    reply:"Tap or insert.",
    alt:"Do you take Apple Pay?" },
  { en:"Could I have a bag, please?", zh:"能给个袋子吗？", freq:1,
    tip:"很多国家袋子收费，会接一句 That's ten cents.",
    reply:"Bags are five cents each.",
    alt:"Could I get a receipt?" }
]},
{ id:"refund", group:"shop", name:"退换货", en:"Returns", icon:"↩️", lines:[
  { en:"I'd like to return this, please.", zh:"我想退掉这个。", freq:3,
    tip:"带上小票 receipt。想换不想退就说 exchange。",
    reply:"Do you have the receipt?",
    alt:"I'd like to exchange this for a bigger size." },
  { en:"It doesn't fit.", zh:"尺码不合适。", freq:2,
    tip:"最省事的退货理由，对方一般不再追问。",
    reply:"No problem, I'll process the refund.",
    alt:"I changed my mind." },
  { en:"Can I get a refund instead of store credit?", zh:"能退钱而不是给购物卡吗？", freq:1,
    tip:"store credit = 只能在本店用的余额，很多店默认给这个。",
    reply:"Since you have the receipt, yes.",
    alt:"How long does the refund take?" }
]},

/* ============ 生活 ============ */
{ id:"grocery", group:"life", name:"超市便利店", en:"Grocery Store", icon:"🛒", lines:[
  { en:"Excuse me, where can I find the milk?", zh:"请问牛奶在哪儿？", freq:3,
    tip:"where can I find ... 是找东西的标准问法，换任何商品都行。",
    reply:"Aisle six, on your right.",
    alt:"Which aisle is the bread in?" },
  { en:"No bag, thanks.", zh:"不用袋子，谢谢。", freq:2,
    tip:"结账时最常被问的一句，提前准备好答案。",
    reply:"Okay. That's twelve forty.",
    alt:"I brought my own bag." },
  { en:"Sorry, I think this rang up wrong.", zh:"不好意思，这个好像扫错价了。", freq:1,
    tip:"ring up = 收银机扫出的价格。用 I think 开头不会显得咄咄逼人。",
    reply:"Let me check that for you.",
    alt:"Wasn't this on sale?" }
]},
{ id:"doctor", group:"life", name:"看病", en:"Seeing a Doctor", icon:"🏥", lines:[
  { en:"I've had a sore throat for three days.", zh:"我嗓子疼三天了。", freq:3,
    tip:"症状+时长一起说，医生最需要这两个信息。sore throat 嗓子疼 / headache 头疼 / fever 发烧。",
    reply:"Any fever? Let me take a look.",
    alt:"I have a bad stomachache." },
  { en:"I'm allergic to penicillin.", zh:"我对青霉素过敏。", freq:2,
    tip:"进诊室就主动说，比等着被问安全。",
    reply:"Good to know, I'll note that.",
    alt:"I'm not allergic to anything." },
  { en:"Do I need a prescription for this?", zh:"这个需要处方吗？", freq:1,
    tip:"prescription 处方；over-the-counter 是非处方、药店直接买。",
    reply:"I'll write you one.",
    alt:"Could I get a receipt for my insurance?" }
]},
{ id:"pharmacy", group:"life", name:"药店", en:"Pharmacy", icon:"💊", lines:[
  { en:"Do you have anything for a cold?", zh:"有治感冒的药吗？", freq:3,
    tip:"不知道药名就说症状，店员会给你拿。for a cough 咳嗽 / for a headache 头疼。",
    reply:"This one works well — take it twice a day.",
    alt:"Something for an upset stomach, please." },
  { en:"How often should I take it?", zh:"多久吃一次？", freq:2,
    tip:"吃药说 take，不说 eat。",
    reply:"Two tablets every six hours.",
    alt:"Before or after meals?" },
  { en:"Is there a non-drowsy version?", zh:"有不犯困的吗？", freq:1,
    tip:"drowsy 犯困。白天要开车、上班时很有用。",
    reply:"Yes, this one won't make you sleepy.",
    alt:"Are there any side effects?" }
]},
{ id:"bank", group:"life", name:"银行换钱", en:"Bank & Money", icon:"🏦", lines:[
  { en:"I'd like to exchange some money, please.", zh:"我想换点钱。", freq:3,
    tip:"exchange money 换汇。接着说 dollars into euros 就清楚了。",
    reply:"How much would you like to change?",
    alt:"Could I change these into euros?" },
  { en:"What's the exchange rate today?", zh:"今天汇率多少？", freq:2,
    tip:"跟着问一句 Is there a fee?（有手续费吗）能少踩坑。",
    reply:"It's 1.08, with a three-dollar fee.",
    alt:"Is there a commission?" },
  { en:"Could I get some smaller bills?", zh:"能给点小面额的吗？", freq:1,
    tip:"大钞很多小店不收，换钱时顺口提一句。",
    reply:"Sure, how would you like it?",
    alt:"Could I have some coins for the bus?" }
]},
{ id:"haircut", group:"life", name:"理发", en:"Haircut", icon:"✂️", lines:[
  { en:"Just a trim, please — about an inch.", zh:"稍微修一下就行，大概一英寸。", freq:3,
    tip:"trim = 修剪不改型，是最保险的说法。一英寸约 2.5 厘米。",
    reply:"Same style, just shorter?",
    alt:"Not too short, please." },
  { en:"Could you keep the length on top?", zh:"上面的长度能留着吗？", freq:2,
    tip:"top 头顶 / sides 两侧 / back 后面，分区说最不容易剪坏。",
    reply:"So short on the sides, long on top?",
    alt:"Shorter on the sides, please." },
  { en:"That's great, thank you.", zh:"很好，谢谢。", freq:1,
    tip:"照镜子确认时说的收尾句。想再短一点就说 A little shorter, please.",
    reply:"Glad you like it!",
    alt:"Could you take a bit more off?" }
]},
{ id:"sim", group:"life", name:"手机网络", en:"Phone & Internet", icon:"📶", lines:[
  { en:"I'd like a SIM card with data, please.", zh:"我想要一张有流量的卡。", freq:3,
    tip:"data 就是流量。现在也可以说 an eSIM。",
    reply:"How long are you staying?",
    alt:"Do you have prepaid SIM cards?" },
  { en:"How much data does that include?", zh:"这个套餐含多少流量？", freq:2,
    tip:"套餐是 plan。问清是 unlimited（不限量）还是几个 GB。",
    reply:"Ten gigs for thirty days.",
    alt:"Is it unlimited?" },
  { en:"Could you help me set it up?", zh:"能帮我设置一下吗？", freq:1,
    tip:"set up 设置/开通。店员通常很乐意当场弄好。",
    reply:"Sure, hand me your phone.",
    alt:"It's not connecting — could you take a look?" }
]}
,
/* ============ 社交 ============ */
{ id:"meet", group:"social", name:"初次见面", en:"Meeting Someone", icon:"🤝", lines:[
  { en:"Hi, I'm Chen. Nice to meet you.", zh:"你好，我是陈。很高兴认识你。", freq:3,
    tip:"标准三段：打招呼+报名字+客套。对方回 Nice to meet you too.",
    reply:"Nice to meet you too — I'm Sarah.",
    alt:"Hi, I'm Chen — good to meet you." },
  { en:"Sorry, I didn't catch your name.", zh:"抱歉，我没听清你的名字。", freq:2,
    tip:"catch 这里是听清。比 What's your name again? 自然得多。",
    reply:"It's Sarah. S-A-R-A-H.",
    alt:"How do you spell that?" },
  { en:"So what do you do?", zh:"你是做什么的？", freq:1,
    tip:"英语里问职业就是 What do you do，别加 job。",
    reply:"I work in marketing. How about you?",
    alt:"What brings you here?" }
]},
{ id:"smalltalk", group:"social", name:"闲聊寒暄", en:"Small Talk", icon:"💬", lines:[
  { en:"How's it going?", zh:"最近怎么样？", freq:3,
    tip:"最自然的日常问候，等于 How are you，但更口语。回一句 Good, you? 就够。",
    reply:"Pretty good, you?",
    alt:"How've you been?" },
  { en:"Yeah, tell me about it.", zh:"可不是嘛。", freq:2,
    tip:"表示强烈同意，不是真让对方讲。对方抱怨天气、堵车时接这句最地道。",
    reply:"Right? It's been like this all week.",
    alt:"I know, right?" },
  { en:"That sounds great!", zh:"听起来不错啊！", freq:1,
    tip:"万能捧场句。听到坏消息就换 That's too bad.",
    reply:"Yeah, I'm pretty excited.",
    alt:"Oh, that's interesting." }
]},
{ id:"invite", group:"social", name:"邀约", en:"Making Plans", icon:"📅", lines:[
  { en:"Do you want to grab a coffee sometime?", zh:"改天一起喝杯咖啡？", freq:3,
    tip:"grab 让邀请显得随意不有压力，是英语约人的标配动词。",
    reply:"Sure, I'd love to.",
    alt:"Are you free this weekend?" },
  { en:"Does Friday work for you?", zh:"周五方便吗？", freq:2,
    tip:"work for you = 对你合适吗，定时间的标准问法。",
    reply:"Friday works. What time?",
    alt:"What time works best?" },
  { en:"Sorry, I can't make it — maybe next time?", zh:"抱歉我去不了，下次吧？", freq:1,
    tip:"make it = 能到场。加一句 maybe next time 就不会显得冷淡。",
    reply:"No worries, next time!",
    alt:"I'd love to, but I'm tied up that day." }
]},
{ id:"thanks", group:"social", name:"道谢与回应", en:"Thanks", icon:"🙏", lines:[
  { en:"Thanks so much, I really appreciate it.", zh:"太感谢了，真的帮大忙了。", freq:3,
    tip:"比单说 thank you 有分量，别人帮了实忙时用。",
    reply:"Happy to help!",
    alt:"Thank you, that's really kind of you." },
  { en:"No worries.", zh:"没事儿 / 不客气。", freq:2,
    tip:"回应道谢和道歉都能用，全世界英语区最常听到的一句。",
    reply:"—",
    alt:"You're welcome. / No problem." },
  { en:"You didn't have to do that!", zh:"你太客气了！", freq:1,
    tip:"收到礼物或额外照顾时说，语气是惊喜不是责怪。",
    reply:"It was nothing.",
    alt:"That's so thoughtful of you." }
]},
{ id:"sorry", group:"social", name:"道歉", en:"Apologizing", icon:"😅", lines:[
  { en:"Sorry about that.", zh:"不好意思啊。", freq:3,
    tip:"小事道歉万能句：撞到人、说错话、拿错东西都能用。",
    reply:"No worries.",
    alt:"Oops, sorry!" },
  { en:"Sorry to keep you waiting.", zh:"抱歉让你久等了。", freq:2,
    tip:"迟到或让人等时的标准句，比空说 sorry 具体。",
    reply:"That's okay, I just got here.",
    alt:"Sorry I'm late — traffic was bad." },
  { en:"That's my fault — I should have checked.", zh:"是我的问题，我该先确认的。", freq:1,
    tip:"工作场合把责任说清楚反而加分。should have + 过去分词 = 本该做而没做。",
    reply:"It's fine, let's fix it.",
    alt:"I'll take care of it." }
]},
{ id:"bye", group:"social", name:"告别", en:"Saying Goodbye", icon:"👋", lines:[
  { en:"It was nice meeting you.", zh:"很高兴认识你。", freq:3,
    tip:"注意是过去式：初次见面告别时用。老朋友告别说 Good seeing you.",
    reply:"You too! Take care.",
    alt:"Great talking to you." },
  { en:"Take care!", zh:"保重！", freq:2,
    tip:"温度刚好的告别，同事、店员、朋友都能用。",
    reply:"You too, bye!",
    alt:"Have a good one!" },
  { en:"Let's keep in touch.", zh:"保持联系啊。", freq:1,
    tip:"想继续联系就接一句 What's your WeChat / number?",
    reply:"Definitely — I'll message you.",
    alt:"See you around." }
]},

/* ============ 工作 ============ */
{ id:"intro", group:"work", name:"自我介绍", en:"Introducing Yourself", icon:"🧑‍💼", lines:[
  { en:"I'm Chen, I work on the product team.", zh:"我是陈，在产品团队。", freq:3,
    tip:"名字+部门/角色一句带过，职场介绍别背长稿。",
    reply:"Nice to meet you — I'm on the design side.",
    alt:"I'm Chen, I handle the China market." },
  { en:"I've been with the company for three years.", zh:"我在这家公司三年了。", freq:2,
    tip:"现在完成进行时，表示到现在还在做。",
    reply:"Oh nice, so you know everyone.",
    alt:"I just joined last month." },
  { en:"Feel free to reach out anytime.", zh:"有事随时找我。", freq:1,
    tip:"reach out 是职场里联系的标准说法，收尾很得体。",
    reply:"Thanks, I will.",
    alt:"Let me know if you need anything." }
]},
{ id:"meeting", group:"work", name:"开会发言", en:"In a Meeting", icon:"📊", lines:[
  { en:"Sorry, could I jump in here?", zh:"抱歉，我插一句。", freq:3,
    tip:"抢发言权的礼貌方式。别硬打断，用这句几乎没人会拒绝。",
    reply:"Sure, go ahead.",
    alt:"Can I add something quickly?" },
  { en:"Just to make sure I understand — you mean ...?", zh:"我确认一下，你的意思是……？", freq:2,
    tip:"确认理解比装懂强一百倍，还显得你在认真听。",
    reply:"Exactly. / Not quite — what I mean is ...",
    alt:"So if I'm following you correctly ...?" },
  { en:"Let me get back to you on that.", zh:"这个我回头答复你。", freq:1,
    tip:"当场答不上来时的高情商回答，不是敷衍，是给自己留时间。",
    reply:"Sure, by end of day?",
    alt:"I'll look into it and follow up." }
]},
{ id:"phone", group:"work", name:"打电话", en:"On the Phone", icon:"📞", lines:[
  { en:"Hi, this is Chen calling about the order.", zh:"你好，我是陈，关于订单的事。", freq:3,
    tip:"电话里介绍自己用 this is，不用 I am。加上事由对方更快进入状态。",
    reply:"Hi Chen, how can I help?",
    alt:"Hi, it's Chen from the Shanghai office." },
  { en:"Sorry, you're breaking up — could you say that again?", zh:"抱歉信号不好，能再说一遍吗？", freq:2,
    tip:"break up 指信号断断续续，电话专用表达。",
    reply:"Can you hear me now?",
    alt:"The line's a bit bad." },
  { en:"Could you hold on a second?", zh:"稍等一下好吗？", freq:1,
    tip:"hold on 电话里等一下。回来说 Thanks for holding.",
    reply:"Sure, no problem.",
    alt:"Let me put you on hold for a moment." }
]},
{ id:"request", group:"work", name:"请求与请假", en:"Requests", icon:"📮", lines:[
  { en:"Would it be possible to move the meeting to Thursday?", zh:"会议能改到周四吗？", freq:3,
    tip:"Would it be possible to ... 是职场最稳的请求句型，几乎不会得罪人。",
    reply:"Let me check my calendar.",
    alt:"Could we reschedule?" },
  { en:"I'd like to take Friday off.", zh:"我想周五请假。", freq:2,
    tip:"take a day off 请假。病假是 sick day。",
    reply:"That should be fine — put it in the system.",
    alt:"I'm taking a sick day today." },
  { en:"Could you send me the file when you get a chance?", zh:"你方便的时候把文件发我一下？", freq:1,
    tip:"when you get a chance 一加，催活儿也不催命。",
    reply:"Will do, in about an hour.",
    alt:"Any update on this?" }
]},

/* ============ 应急 ============ */
{ id:"repeat", group:"sos", name:"没听懂", en:"I Didn't Catch That", icon:"🔁", lines:[
  { en:"Sorry, could you say that again?", zh:"抱歉，能再说一遍吗？", freq:3,
    tip:"全场最该背熟的一句。永远不要因为没听懂就点头。",
    reply:"Sure — I said the bus leaves at six.",
    alt:"Sorry, I didn't catch that." },
  { en:"Could you speak a little slower, please?", zh:"能说慢一点吗？", freq:2,
    tip:"比让人重复更管用，重复一遍还是快等于白搭。",
    reply:"Of course, sorry.",
    alt:"My English isn't great — slower, please?" },
  { en:"What does that mean?", zh:"那是什么意思？", freq:1,
    tip:"遇到没听过的词直接问，母语者通常很愿意解释。",
    reply:"It means you get one free.",
    alt:"Sorry, what's ... ?" }
]},
{ id:"help", group:"sos", name:"求助", en:"Getting Help", icon:"🆘", lines:[
  { en:"Excuse me, could you help me?", zh:"打扰一下，能帮我个忙吗？", freq:3,
    tip:"任何求助的起手式。紧急情况直接喊 I need help!",
    reply:"Sure, what's up?",
    alt:"Sorry to bother you — I need some help." },
  { en:"I think I'm lost.", zh:"我好像迷路了。", freq:2,
    tip:"配合手机地图一起用，对方通常会直接给你指。",
    reply:"Where are you trying to go?",
    alt:"I can't find my hotel." },
  { en:"Could you call an ambulance?", zh:"能叫救护车吗？", freq:1,
    tip:"ambulance 救护车 / the police 警察。危急时刻不用讲礼貌，直接说。",
    reply:"Stay here, help is coming.",
    alt:"Call the police, please!" }
]},
{ id:"lost", group:"sos", name:"丢东西", en:"Lost & Stolen", icon:"🎒", lines:[
  { en:"I lost my phone — I think I left it in the taxi.", zh:"我手机丢了，好像落在出租车上了。", freq:3,
    tip:"丢什么+可能落在哪，一句说完最有助于找回。",
    reply:"Do you have the receipt or the plate number?",
    alt:"I can't find my bag." },
  { en:"My wallet was stolen.", zh:"我的钱包被偷了。", freq:2,
    tip:"stolen 被偷（有人拿走），lost 是自己丢的，报案时说法不同。",
    reply:"You'll need to file a report.",
    alt:"Someone took my suitcase." },
  { en:"I need to report it for my insurance.", zh:"我需要报案给保险公司用。", freq:1,
    tip:"没有警方报案单，保险基本不赔。记得要 a copy of the report。",
    reply:"Come this way, I'll take your statement.",
    alt:"Could I get a copy of the report?" }
]},

/* ============ 东南亚 ============ */
{ id:"bargain", group:"sea", name:"砍价", en:"Bargaining", icon:"💰", lines:[
  { en:"How much for two?", zh:"两个多少钱？", freq:3,
    tip:"东南亚市场砍价第一步：先问打包价，价格自动就降了。别一上来问单价。",
    reply:"Five hundred for two, good price!",
    alt:"What's your best price?" },
  { en:"That's too expensive. Can you do two hundred?", zh:"太贵了，两百行吗？", freq:2,
    tip:"直接报你的价，一般从对方开价的四到五折开始还。语气笑着说，别板脸。",
    reply:"Two fifty, okay? Last price.",
    alt:"Can you give me a discount?" },
  { en:"Okay, thanks anyway.", zh:"好吧，还是谢谢。", freq:1,
    tip:"转身要走是最强的砍价动作，八成会被叫回去。说完真的迈步。",
    reply:"Okay okay, two hundred! Come back!",
    alt:"Maybe next time." }
]},
{ id:"tuktuk", group:"sea", name:"嘟嘟车摩的", en:"Tuk-tuk & Motorbike", icon:"🛺", lines:[
  { en:"How much to the night market?", zh:"到夜市多少钱？", freq:3,
    tip:"东南亚必须上车前谈好价，不然到地方一定加价。问完再砍一轮。",
    reply:"Two hundred baht.",
    alt:"How much to go there?" },
  { en:"Meter, please.", zh:"请打表。", freq:2,
    tip:"曼谷正规出租车必须打表。司机说 meter broken 就换一辆，别争。",
    reply:"No meter, fixed price.",
    alt:"Can you turn on the meter?" },
  { en:"Do you have a helmet?", zh:"有头盔吗？", freq:1,
    tip:"坐摩的一定要，很多国家不戴要罚款，安全更重要。",
    reply:"Yes, here you go.",
    alt:"Please go slowly." }
]},
{ id:"street", group:"sea", name:"街边小吃", en:"Street Food", icon:"🍜", lines:[
  { en:"Not spicy, please.", zh:"不要辣，谢谢。", freq:3,
    tip:"东南亚的 a little spicy 也可能辣到怀疑人生。想保命就说 no spicy at all。",
    reply:"Okay, no chili.",
    alt:"A little spicy is okay." },
  { en:"One of these, please.", zh:"这个来一份。", freq:2,
    tip:"看不懂菜名就指着说这句，全世界通用，配手势最有效。",
    reply:"Eat here or take away?",
    alt:"Two of those, please." },
  { en:"Take away, please.", zh:"打包带走。", freq:1,
    tip:"东南亚英语里 take away 比美式 to go 更通用，摊主一听就懂。",
    reply:"Okay, one minute.",
    alt:"Is the water safe to drink?" }
]},
{ id:"temple", group:"sea", name:"寺庙礼仪", en:"Temples", icon:"🛕", lines:[
  { en:"Should I take off my shoes?", zh:"需要脱鞋吗？", freq:3,
    tip:"进殿几乎都要脱鞋，问一句最保险。对你这行来说，礼数到位也是专业。",
    reply:"Yes, please leave them here.",
    alt:"Where should I leave my shoes?" },
  { en:"Is it okay to take photos here?", zh:"这里可以拍照吗？", freq:2,
    tip:"佛像和僧人拍照很多地方有忌讳，先问再拍。",
    reply:"Outside is fine, not inside.",
    alt:"Can I take a picture with you?" },
  { en:"Am I dressed okay to go in?", zh:"我这身衣服能进去吗？", freq:1,
    tip:"露肩短裤常被拦，门口一般有围布可借：Can I borrow a sarong?",
    reply:"You'll need to cover your shoulders.",
    alt:"Do I need to cover up?" }
]},
{ id:"massage", group:"sea", name:"按摩SPA", en:"Massage & Spa", icon:"💆", lines:[
  { en:"How much for an hour?", zh:"一小时多少钱？", freq:3,
    tip:"先问时长价格，再选项目。Thai massage 泰式 / oil massage 精油 / foot 足底。",
    reply:"Three hundred for one hour.",
    alt:"Do you have a two-hour package?" },
  { en:"A bit softer, please.", zh:"轻一点。", freq:2,
    tip:"泰式力度真的很大。重一点是 A bit stronger, please.",
    reply:"Okay, like this?",
    alt:"That's a little too strong." },
  { en:"Could you focus on my shoulders?", zh:"能重点按肩膀吗？", freq:1,
    tip:"focus on + 部位：back 背 / neck 脖子 / legs 腿。久坐族必备。",
    reply:"Sure, shoulders are very tight.",
    alt:"My lower back hurts." }
]},
{ id:"island", group:"sea", name:"海岛跳岛", en:"Island Hopping", icon:"🏝️", lines:[
  { en:"What time does the boat leave?", zh:"船几点开？", freq:3,
    tip:"东南亚船期常变，头天再确认一次。回程是 the last boat back。",
    reply:"Nine thirty from the pier.",
    alt:"When's the last boat back?" },
  { en:"Is lunch included in the tour?", zh:"这个行程含午饭吗？", freq:2,
    tip:"跟团先问清含什么：lunch / snorkeling gear / entrance fee 门票。",
    reply:"Yes, and snorkeling gear too.",
    alt:"What's included in the price?" },
  { en:"Where do we meet after?", zh:"结束后在哪儿集合？", freq:1,
    tip:"跳岛游最容易走散，上岛前一定问清集合点和时间。",
    reply:"Right here, at three o'clock.",
    alt:"How long do we have here?" }
]},
{ id:"charter", group:"sea", name:"包车包船", en:"Hiring a Driver", icon:"🚐", lines:[
  { en:"How much for the whole day?", zh:"包一天多少钱？", freq:3,
    tip:"东南亚包车比打表划算得多，谈好总价再确认包几小时。",
    reply:"Two thousand for eight hours.",
    alt:"How many hours does that include?" },
  { en:"Does that include gas and parking?", zh:"含油费和停车费吗？", freq:2,
    tip:"最常见的加价点就在这里，一定当场问明白。",
    reply:"Gas yes, parking you pay.",
    alt:"Any extra fees I should know about?" },
  { en:"Could you wait for us here?", zh:"你能在这儿等我们吗？", freq:1,
    tip:"景点停留时说，加一句 about an hour 让司机心里有数。",
    reply:"Okay, I'll be right here.",
    alt:"We'll be about an hour." }
]},
{ id:"scam", group:"sea", name:"拒绝拉客", en:"Saying No", icon:"🙅", lines:[
  { en:"No, thank you.", zh:"不用了，谢谢。", freq:3,
    tip:"拉客的最怕坚定简短。说完继续走，别停下、别解释、别对视。",
    reply:"（对方一般就走开了）",
    alt:"I'm all set, thanks." },
  { en:"I'm not interested, thanks.", zh:"我没兴趣，谢谢。", freq:2,
    tip:"对纠缠不放的人升一级语气。仍然带 thanks，不至于起冲突。",
    reply:"Just look, no buy!",
    alt:"Please stop following me." },
  { en:"Sorry, the temple is closed today? Let me check myself.", zh:"抱歉，说寺庙今天关门？我自己确认一下。", freq:1,
    tip:"经典骗局就是告诉你景点关门，带你去别处购物。永远自己核实。",
    reply:"No no, I take you to better place!",
    alt:"I'll take a metered taxi, thanks." }
]},

/* ============ 易经专业口语 ============ */
{ id:"myfield", group:"yijing", name:"介绍我的行业", en:"What I Do", icon:"☯️", lines:[
  { en:"I study Chinese metaphysics — the Yijing, or Book of Changes.", zh:"我研究中国术数，也就是《易经》。", freq:3,
    tip:"Chinese metaphysics 是这一行公认的英文说法，比 fortune-telling 专业得多，一开口就定调。老外多半听过 I Ching。",
    reply:"Oh, the I Ching! I've heard of that.",
    alt:"I work with the Yijing and Chinese astrology." },
  { en:"It's a traditional system for reading patterns of change.", zh:"它是一套解读变化规律的传统体系。", freq:2,
    tip:"对方追问时的第一层解释。patterns of change 抓住了易的本义，也不玄。",
    reply:"So it's like philosophy, or fortune-telling?",
    alt:"It's part philosophy, part practical method." },
  { en:"I do readings, and I also teach.", zh:"我做咨询，也教学。", freq:1,
    tip:"reading = 一次解读/咨询，是这行最标准的说法。别用 fortune-telling 自称。",
    reply:"How long have you been doing this?",
    alt:"I've been practicing for over ten years." }
]},
{ id:"exp_iching", group:"yijing", name:"解释《易经》", en:"Explaining the Yijing", icon:"📖", lines:[
  { en:"The Yijing is a three-thousand-year-old Chinese classic.", zh:"《易经》是一部三千年的中国经典。", freq:3,
    tip:"先给年代和身份，老外立刻有画面。Yijing 和 I Ching 是同一个词的新旧拼法，都能用。",
    reply:"Three thousand years? Wow.",
    alt:"It's one of the oldest books in Chinese culture." },
  { en:"It uses sixty-four hexagrams — six-line symbols — to describe situations.", zh:"它用六十四个卦、每卦六爻，来描述各种处境。", freq:2,
    tip:"hexagram 六爻卦 / trigram 三爻卦，一定要分清。加一句 six-line symbols 老外秒懂。",
    reply:"How do you get a hexagram?",
    alt:"Each hexagram is made of two trigrams." },
  { en:"You cast a hexagram with coins, then read what it points to.", zh:"用铜钱起卦，然后解读它指向什么。", freq:1,
    tip:"cast a hexagram = 起卦，行业标准表达。古法说 with yarrow stalks（蓍草）。",
    reply:"Can you show me?",
    alt:"Traditionally, with yarrow stalks." }
]},
{ id:"exp_bazi", group:"yijing", name:"解释八字", en:"Explaining BaZi", icon:"🀄", lines:[
  { en:"BaZi is Chinese astrology based on your birth date and time.", zh:"八字是根据出生年月日时来看的中国命理。", freq:3,
    tip:"用 Chinese astrology 搭桥，老外马上有参照系，再纠正细节。",
    reply:"Like Western astrology?",
    alt:"We call it the Four Pillars of Destiny." },
  { en:"It's called the Four Pillars — year, month, day, and hour.", zh:"叫四柱：年、月、日、时。", freq:2,
    tip:"Four Pillars of Destiny 是国际通用译名，报出来很有分量。",
    reply:"So you need my exact birth time?",
    alt:"Each pillar has two characters, eight in total." },
  { en:"It doesn't predict events — it shows tendencies and timing.", zh:"它不预测具体事件，看的是趋势和时机。", freq:1,
    tip:"这句能一次性挡掉九成的误解和抬杠，也是很好的专业边界声明。",
    reply:"That makes sense.",
    alt:"Think of it as a map, not a script." }
]},
{ id:"exp_fs", group:"yijing", name:"解释风水", en:"Explaining Feng Shui", icon:"🧭", lines:[
  { en:"Feng shui is about how a space affects the people in it.", zh:"风水讲的是环境如何影响住在里面的人。", freq:3,
    tip:"避开玄学词，先说人人能懂的因果，老外接受度最高。",
    reply:"Like interior design?",
    alt:"Literally it means wind and water." },
  { en:"We look at the landform first, then the compass direction.", zh:"先看形势，再看理气方位。", freq:2,
    tip:"form school 形家 / compass school 理气派，是英文风水书里的固定叫法，说出来很内行。",
    reply:"What's that instrument called?",
    alt:"There are two main schools: form and compass." },
  { en:"This is a luopan — a Chinese geomantic compass.", zh:"这是罗盘，中国的堪舆罗盘。", freq:1,
    tip:"geomancy/geomantic 是风水的学术英文词，配合罗盘实物讲，效果最好。",
    reply:"What are all these rings for?",
    alt:"Each ring carries a different layer of information." }
]},
{ id:"consult_open", group:"yijing", name:"咨询开场", en:"Starting a Reading", icon:"🗓️", lines:[
  { en:"Could you give me your birth date, time, and place?", zh:"能给我你的出生日期、时间和地点吗？", freq:3,
    tip:"三样缺一不可。birth data 是这行的专用词，可直接说 I'll need your birth data。",
    reply:"March 5th, 1989, around 7 a.m., in Sydney.",
    alt:"I'll need your birth data first." },
  { en:"Do you know the exact hour you were born?", zh:"你知道自己出生的准确时辰吗？", freq:2,
    tip:"老外常常不知道时辰。可以接一句 An approximate time still works.",
    reply:"Not exactly — sometime in the morning.",
    alt:"Even an approximate time helps." },
  { en:"Is there something specific you'd like to look at?", zh:"你有特别想看的方面吗？", freq:1,
    tip:"把话题收窄，一小时才讲得完。career 事业 / relationship 感情 / health 健康 / timing 时机。",
    reply:"Mainly my career, I think.",
    alt:"Career, relationships, or timing?" }
]},
{ id:"consult_read", group:"yijing", name:"解读与建议", en:"Giving a Reading", icon:"🔮", lines:[
  { en:"Your chart shows a strong Wood element.", zh:"你的命盘木很旺。", freq:3,
    tip:"chart = 命盘/卦盘。五行英文：Wood 木 / Fire 火 / Earth 土 / Metal 金 / Water 水，首字母大写显专业。",
    reply:"What does Wood mean?",
    alt:"Your Day Master is Water, born in winter." },
  { en:"This suggests the next two years favor change.", zh:"这显示未来两年宜变动。", freq:2,
    tip:"用 suggests / tends to / favors 这类软动词，既准确又不把话说死。",
    reply:"Should I take the new job then?",
    alt:"The timing tends to support a move." },
  { en:"My suggestion would be to wait until spring.", zh:"我的建议是等到春天。", freq:1,
    tip:"My suggestion would be ... 比 You should ... 得体，把决定权留给对方。",
    reply:"That's helpful, thank you.",
    alt:"You might want to hold off for now." }
]},
{ id:"disclaimer", group:"yijing", name:"边界与免责", en:"Setting Boundaries", icon:"⚖️", lines:[
  { en:"I read tendencies, not certainties.", zh:"我看的是趋势，不是定论。", freq:3,
    tip:"开场就说这一句，能省掉后面所有麻烦，专业感也最强。",
    reply:"Fair enough.",
    alt:"Nothing here is set in stone." },
  { en:"I don't give medical or legal advice.", zh:"我不提供医疗或法律建议。", freq:2,
    tip:"必须划清的红线。被问健康就接 Please see a doctor for that.",
    reply:"Of course, I understand.",
    alt:"For that, you'd want a professional in that field." },
  { en:"I'd rather not read on questions about life and death.", zh:"生死的问题我不看。", freq:1,
    tip:"I'd rather not 是最柔和的拒绝，行规也如此，说出来对方通常很尊重。",
    reply:"No problem, I won't ask.",
    alt:"That's outside what I do." }
]},
{ id:"biz", group:"yijing", name:"收费与交流", en:"Fees & Networking", icon:"💼", lines:[
  { en:"A full reading is one hour, and it's a hundred and fifty dollars.", zh:"完整一次一小时，一百五十美元。", freq:3,
    tip:"时长+价格一句说完，最不尴尬。东南亚可按当地货币，先说 in US dollars 更清楚。",
    reply:"Do you take card?",
    alt:"My rate is one fifty per session." },
  { en:"We can do it online — I'll send you the chart afterwards.", zh:"可以线上做，结束后我把命盘发你。", freq:2,
    tip:"跨国客户必备。afterwards 表示事后，比 later 正式。",
    reply:"Great, over Zoom?",
    alt:"I'll email you a written summary." },
  { en:"I'm running a workshop next month — you're welcome to join.", zh:"我下个月有个工作坊，欢迎参加。", freq:1,
    tip:"workshop 工作坊 / talk 讲座 / class 课程。交流会上顺势递出这句最自然。",
    reply:"I'd love to. How do I sign up?",
    alt:"Here's my contact — let's stay in touch." }
]}
];

/* ============================================================
 * 专业单词本 · 易经文化行业英文
 * 给「用英语跟外国人谈这一行」用：术语 + 一句英文释义 + 怎么说不踩坑
 *   en 英文术语 | zh 中文 | py 拼音式/音译写法（老外圈子里常见的拼法）
 *   def 一句英文释义（可以直接背下来当解释用）
 *   note 用法提示、常见误用
 * ============================================================ */
const TERMSETS = [
{ id:"core", name:"总纲", en:"Core Concepts", icon:"☯️", terms:[
  { en:"Chinese metaphysics", zh:"中国术数（总称）", py:"shu shu",
    def:"The umbrella term for Chinese systems of fate, divination and space.",
    note:"介绍自己这一行的最佳用词。比 fortune-telling 专业，也不带贬义。" },
  { en:"the Yijing / the I Ching", zh:"《易经》", py:"Yi Jing",
    def:"The Book of Changes, a Chinese classic of sixty-four hexagrams.",
    note:"I Ching 是老拼法（威妥玛），西方最熟；Yijing 是拼音写法，学术圈用。读作 /iː dʒɪŋ/。" },
  { en:"Book of Changes", zh:"《易经》英译名", py:"—",
    def:"The standard English title of the Yijing.",
    note:"第一次提《易经》就用 the Yijing, or Book of Changes，一次说清。" },
  { en:"divination", zh:"占卜", py:"zhan bu",
    def:"The practice of seeking insight into a question by a formal method.",
    note:"中性学术词，比 fortune-telling 好。动词是 to divine。" },
  { en:"practitioner", zh:"从业者 / 术者", py:"—",
    def:"Someone who practices a discipline professionally.",
    note:"自称首选：I'm a practitioner of Chinese metaphysics。别自称 master，让别人说。" },
  { en:"reading", zh:"一次解读 / 咨询", py:"—",
    def:"A session in which a practitioner interprets a chart or hexagram.",
    note:"这行最核心的业务词：do a reading / book a reading / a full reading。" },
  { en:"chart", zh:"命盘 / 盘", py:"—",
    def:"The diagram of someone's birth data used for interpretation.",
    note:"八字盘、紫微盘都叫 chart。起盘是 to cast / draw up a chart。" },
  { en:"fate / destiny", zh:"命", py:"ming",
    def:"The given conditions of a life, as opposed to what one does with them.",
    note:"讲命理三才时可说 fate, luck and effort（命、运、人为）。" },
  { en:"cosmology", zh:"宇宙观 / 天人体系", py:"—",
    def:"A worldview of how heaven, earth and humans relate.",
    note:"跟受过教育的老外解释体系背景时非常好用的词。" },
  { en:"correlative thinking", zh:"类象思维 / 取象", py:"qu xiang",
    def:"Reasoning by resonance between categories rather than by cause and effect.",
    note:"解释「为什么木对应春天和肝」时用这个词，学术界通行，一说对方就服。" }
]},
{ id:"yinyang", name:"阴阳五行", en:"Yin-Yang & Five Phases", icon:"🌗", terms:[
  { en:"yin and yang", zh:"阴阳", py:"yin yang",
    def:"Two complementary aspects that define each other, like shade and sunlight.",
    note:"已进英文词典，不用翻译。强调 complementary（互补）而非 opposite（对立）更准确。" },
  { en:"the Five Phases", zh:"五行", py:"wu xing",
    def:"Wood, Fire, Earth, Metal and Water — five modes of change, not substances.",
    note:"⚠️ Five Elements 是流传最广但不够准的译法；Five Phases 强调「运行」，更内行。" },
  { en:"Wood / Fire / Earth / Metal / Water", zh:"木火土金水", py:"mu huo tu jin shui",
    def:"The names of the five phases, in generating order.",
    note:"作术语时首字母大写，跟普通名词区分：a strong Wood element。" },
  { en:"generating cycle", zh:"相生", py:"xiang sheng",
    def:"Each phase produces the next: Wood feeds Fire, Fire makes Earth.",
    note:"也说 productive cycle / nourishing cycle。" },
  { en:"controlling cycle", zh:"相克", py:"xiang ke",
    def:"Each phase restrains another: Water puts out Fire, Metal cuts Wood.",
    note:"也说 overcoming cycle。别用 destroying，太负面。" },
  { en:"qi", zh:"气", py:"qi",
    def:"Vital energy or activating force that moves through people and places.",
    note:"英文已收录，读 /tʃiː/。别翻成 air。" },
  { en:"balance", zh:"平衡 / 中和", py:"zhong he",
    def:"A state where no single phase overwhelms the others.",
    note:"讲用神取用时的关键词：the chart needs balance。" },
  { en:"excess / deficiency", zh:"太过 / 不及", py:"tai guo / bu ji",
    def:"Too much or too little of a given phase.",
    note:"跟中医英文完全通用，学中医英语的人一听就懂。" }
]},
{ id:"gua", name:"八卦六十四卦", en:"Trigrams & Hexagrams", icon:"䷀", terms:[
  { en:"trigram", zh:"三爻卦 / 八卦之一", py:"gua",
    def:"A symbol of three lines; there are eight of them.",
    note:"⚠️ 最常被说错的词：八卦是 trigram，六十四卦是 hexagram，千万别混。" },
  { en:"hexagram", zh:"六爻卦 / 六十四卦之一", py:"gua",
    def:"A symbol of six lines, formed by stacking two trigrams.",
    note:"读 /ˈheksəɡræm/。六十四卦 = the sixty-four hexagrams。" },
  { en:"line", zh:"爻", py:"yao",
    def:"One of the six horizontal strokes in a hexagram.",
    note:"阳爻 solid line / unbroken line，阴爻 broken line。自下往上数：from the bottom up。" },
  { en:"changing line", zh:"动爻 / 变爻", py:"dong yao",
    def:"A line that transforms into its opposite, giving a second hexagram.",
    note:"也说 moving line。本卦 primary hexagram，变卦 resulting hexagram。" },
  { en:"the eight trigrams", zh:"八卦", py:"ba gua",
    def:"Qian, Kun, Zhen, Xun, Kan, Li, Gen, Dui.",
    note:"英文圈直接用拼音加意译：Qian (Heaven), Kun (Earth), Li (Fire), Kan (Water)。" },
  { en:"the Judgment", zh:"彖辞 / 卦辞", py:"tuan",
    def:"The short text attached to a whole hexagram.",
    note:"卫礼贤译本的固定译名，读过英文《易经》的老外都认这个词。" },
  { en:"the Image", zh:"象辞", py:"xiang",
    def:"The commentary describing the symbolic picture of a hexagram.",
    note:"大象 the Great Image / 小象 the Small Image。" },
  { en:"King Wen sequence", zh:"文王卦序", py:"Wen Wang",
    def:"The traditional order of the sixty-four hexagrams.",
    note:"先天八卦 the Earlier Heaven arrangement / 后天八卦 the Later Heaven arrangement。" }
]},
{ id:"ganzhi", name:"干支历法", en:"Stems, Branches & Calendar", icon:"📅", terms:[
  { en:"Heavenly Stems", zh:"天干", py:"tian gan",
    def:"Ten cyclical signs used with the branches to mark time.",
    note:"十天干 the ten Heavenly Stems，写作 Jia, Yi, Bing, Ding ..." },
  { en:"Earthly Branches", zh:"地支", py:"di zhi",
    def:"Twelve cyclical signs, each linked to an animal and a two-hour period.",
    note:"十二地支 the twelve Earthly Branches：Zi, Chou, Yin, Mao ..." },
  { en:"sexagenary cycle", zh:"六十甲子", py:"jia zi",
    def:"The sixty-year cycle formed by pairing stems and branches.",
    note:"学术标准词。口语可说 the sixty-year cycle 让对方更好懂。" },
  { en:"zodiac animal", zh:"生肖 / 属相", py:"sheng xiao",
    def:"The animal sign attached to a year's earthly branch.",
    note:"老外最熟的入口：What's your Chinese zodiac? 但记得说明生肖只是地支之一。" },
  { en:"solar terms", zh:"二十四节气", py:"jie qi",
    def:"Twenty-four seasonal markers that divide the solar year.",
    note:"⚠️ 八字换月看节气不看初一，一定要解释：we use the solar calendar, not the lunar one。" },
  { en:"lunar calendar", zh:"农历", py:"nong li",
    def:"The traditional Chinese calendar based on moon cycles.",
    note:"也叫 lunisolar calendar，更准确。春节是按它算的。" },
  { en:"the almanac", zh:"通书 / 黄历", py:"tong shu",
    def:"The traditional Chinese calendar-almanac of daily auspices.",
    note:"择日必备。The Chinese almanac, or Tong Shu。" },
  { en:"double hour", zh:"时辰", py:"shi chen",
    def:"A traditional two-hour time period; twelve make a day.",
    note:"解释出生时辰时用：each branch covers two hours。" }
]},
{ id:"bazi", name:"八字命理", en:"BaZi / Four Pillars", icon:"🀄", terms:[
  { en:"Four Pillars of Destiny", zh:"四柱 / 八字", py:"ba zi",
    def:"A birth chart of four stem-branch pairs: year, month, day and hour.",
    note:"国际通用译名。也可直接说 BaZi，圈内人都懂。" },
  { en:"Day Master", zh:"日主 / 日元", py:"ri zhu",
    def:"The stem of the day pillar, representing the person themselves.",
    note:"英文八字书的核心词：My Day Master is Yang Water。" },
  { en:"natal chart", zh:"原局 / 本命盘", py:"yuan ju",
    def:"The fixed chart of the moment of birth.",
    note:"跟大运 luck pillar 对照时用这个词区分。" },
  { en:"luck pillar", zh:"大运", py:"da yun",
    def:"A ten-year period that overlays the natal chart.",
    note:"也说 decade luck / major luck cycle。流年是 the annual pillar。" },
  { en:"the Ten Gods", zh:"十神", py:"shi shen",
    def:"Ten relationships between the Day Master and the other characters.",
    note:"正官 Direct Officer / 七杀 Seven Killings / 正财 Direct Wealth / 食神 Eating God。" },
  { en:"useful god", zh:"用神", py:"yong shen",
    def:"The element the chart most needs in order to come into balance.",
    note:"也译 favourable element，口语里更好懂。忌神 unfavourable element。" },
  { en:"clash", zh:"冲", py:"chong",
    def:"A confrontation between two opposing branches.",
    note:"合 combination / 刑 punishment / 害 harm / 破 destruction，都是固定译法。" },
  { en:"strong or weak", zh:"身强身弱", py:"shen qiang / shen ruo",
    def:"Whether the Day Master has enough support in the chart.",
    note:"a strong Day Master / a weak Day Master，是英文八字讨论的起点。" },
  { en:"self-punishment", zh:"自刑", py:"zi xing",
    def:"A branch that punishes itself when repeated in a chart.",
    note:"讲刑冲时会用到，说完最好举例说明。" }
]},
{ id:"fengshui", name:"风水堪舆", en:"Feng Shui", icon:"🧭", terms:[
  { en:"feng shui", zh:"风水", py:"feng shui",
    def:"The art of siting buildings and graves in harmony with the land and qi.",
    note:"已进英文词典，不必翻译。读 /ˌfʌŋ ˈʃweɪ/，美国人常读成 /fɛŋ ʃuːi/。" },
  { en:"geomancy", zh:"堪舆", py:"kan yu",
    def:"The classical term for reading the earth's configuration.",
    note:"学术场合用它显得正式；日常还是 feng shui 好懂。" },
  { en:"form school", zh:"形势派 / 峦头", py:"luan tou",
    def:"The branch that reads mountains, water and shapes of the land.",
    note:"跟 compass school 对举着说，一句话讲清风水两大分支。" },
  { en:"compass school", zh:"理气派", py:"li qi",
    def:"The branch that works with directions, time cycles and formulas.",
    note:"也说 Li Qi school。你说得出这两个词，对方立刻知道你是内行。" },
  { en:"luopan", zh:"罗盘", py:"luo pan",
    def:"The Chinese geomantic compass, with concentric rings of data.",
    note:"英文里直接用 luopan，加一句 a Chinese geomantic compass 解释。" },
  { en:"sitting and facing", zh:"坐向", py:"zuo xiang",
    def:"The back and front orientation of a building.",
    note:"英文风水书固定说法：the house sits north and faces south。" },
  { en:"dragon vein", zh:"龙脉", py:"long mai",
    def:"The ridgeline along which qi is said to travel through the land.",
    note:"直译最有画面感，讲寻龙点穴时对方很吃这个词。" },
  { en:"the dragon spot", zh:"穴", py:"xue",
    def:"The point where the energy of the land gathers.",
    note:"也说 the lair / the acupoint of the land。点穴 to locate the spot。" },
  { en:"flying stars", zh:"飞星 / 玄空", py:"xuan kong",
    def:"A time-based system that maps nine stars onto a building's grid.",
    note:"Flying Star feng shui 在西方最流行，很多老外只听过这一派。" },
  { en:"the water mouth", zh:"水口", py:"shui kou",
    def:"Where water enters or leaves the site.",
    note:"来水 incoming water / 去水 outgoing water。" },
  { en:"burial site", zh:"阴宅", py:"yin zhai",
    def:"A grave site chosen by geomantic principles.",
    note:"阳宅是 a dwelling / yang dwelling。跟老外提阴宅要先说明这是传统的重要部分。" }
]},
{ id:"methods", name:"术数门类", en:"Other Systems", icon:"🔮", terms:[
  { en:"Da Liu Ren", zh:"大六壬", py:"da liu ren",
    def:"A classical divination system using twelve branches and a heaven plate.",
    note:"英文无通译，直接用拼音加一句解释。课盘是 the plate / the chart。" },
  { en:"Qi Men Dun Jia", zh:"奇门遁甲", py:"qi men dun jia",
    def:"A strategic divination system arranging elements on a nine-palace grid.",
    note:"西方圈子里也直接说 Qi Men，常译作 Mysterious Doors。" },
  { en:"Plum Blossom numerology", zh:"梅花易数", py:"mei hua yi shu",
    def:"A method of casting hexagrams from numbers or observed events.",
    note:"英文常写 Plum Blossom Divination，讲即景起卦时很好用。" },
  { en:"Zi Wei Dou Shu", zh:"紫微斗数", py:"zi wei dou shu",
    def:"A Chinese astrology system placing stars in twelve palaces.",
    note:"常译 Purple Star Astrology，西方接受度高。" },
  { en:"date selection", zh:"择日", py:"ze ri",
    def:"Choosing an auspicious day and hour for an important act.",
    note:"你这行的高频服务词：I do date selection for weddings and openings。" },
  { en:"auspicious / inauspicious", zh:"吉 / 凶", py:"ji / xiong",
    def:"Favourable or unfavourable for a given act at a given time.",
    note:"an auspicious date 吉日，是英文里最标准的说法，别用 lucky day（太随意）。" },
  { en:"the three coins method", zh:"三枚铜钱起卦", py:"—",
    def:"Tossing three coins six times to build a hexagram.",
    note:"起卦演示时的说明词。蓍草古法是 the yarrow stalk method。" },
  { en:"face reading / palm reading", zh:"相术 / 手相", py:"xiang shu",
    def:"Reading character and fortune from the face or hand.",
    note:"physiognomy 是学术词但生僻，口语说 face reading 就好。" }
]},
{ id:"consult", name:"咨询与执业", en:"Consulting", icon:"💼", terms:[
  { en:"birth data", zh:"出生资料", py:"—",
    def:"Date, time and place of birth, needed to cast a chart.",
    note:"一个词要齐三样，比逐个问省事：I'll need your birth data。" },
  { en:"time of birth", zh:"出生时辰", py:"—",
    def:"The exact hour someone was born.",
    note:"追问准确度：Do you know it to the hour? 大概时间是 an approximate time。" },
  { en:"session", zh:"一次咨询", py:"—",
    def:"One appointment with a client.",
    note:"报价单位：per session。a follow-up session 回访。" },
  { en:"remedy / adjustment", zh:"化解 / 调整", py:"hua jie",
    def:"A change suggested to improve an unfavourable configuration.",
    note:"⚠️ 别说 cure（像治病）。风水布局调整说 an adjustment 最稳。" },
  { en:"tendency", zh:"趋势 / 倾向", py:"—",
    def:"What a chart leans toward, rather than what will certainly happen.",
    note:"你的免责核心词：I read tendencies, not certainties。" },
  { en:"timing", zh:"应期 / 时机", py:"ying qi",
    def:"When a situation is most likely to come to a head.",
    note:"客户最关心的就是这个：the timing looks like next spring。" },
  { en:"consultation fee", zh:"咨询费", py:"—",
    def:"What you charge for a reading.",
    note:"报价：My consultation fee is ... 比 price 得体。" },
  { en:"confidential", zh:"保密的", py:"—",
    def:"Kept private between practitioner and client.",
    note:"一句 Everything you tell me stays confidential 能立刻建立信任。" },
  { en:"workshop", zh:"工作坊 / 研习班", py:"—",
    def:"A short hands-on course.",
    note:"讲座 a talk / 课程 a course / 线上课 an online class。" },
  { en:"lineage", zh:"师承 / 传承", py:"shi cheng",
    def:"The line of teachers a practitioner learned from.",
    note:"老外很看重这个：Who did you study with? 答 I study in the ... lineage。" }
]}
];

if (typeof module !== "undefined") module.exports = { GROUPS, SCENES, TERMSETS };
